### ISSUE TITLE
Import HR feed for students and advisors into QA

### ISSUE THREAD

**Issue by kelynch** [pulibrary/drds_catchall#110]
Based on [this timeline](https://docs.google.com/document/d/1glTeD7gl90ABKYHZ_I5ZqzDuQvug4UKrNMtZCqMjtLA/edit).

Between Feb 6 and 10

**Comment by jrgriffiniii** [comment]
https://docs.google.com/spreadsheets/d/1rTlddMH5-yZKpFK2FYb36rqvdnqiwbNDbuqjoe1thdQ/edit?usp=sharing has been cleaned and prepared for export into the TSV required for loading into the QA environment.

**Comment by jrgriffiniii** [comment]
While this is being loaded into the QA environment and reindexed, I have discovered the following: https://github.com/pulibrary/dspace-development/issues/806. I shall address this as a high priority issue and ensure that this is resolved immediately.

**Comment by jrgriffiniii** [comment]
Aside from the X.509 certificate, the import seems to have been successful:
<img width="1364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTlOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85e2f934e5b7bc0342e8133e4ab547bf8c07c289/image.png" alt="image.png" />

**Comment by jrgriffiniii** [comment]
There are some anomalous entries which must be removed manually by executing commands directly to the database server.

**Comment by jrgriffiniii** [comment]
The entries were successfully removed, and the QA sheet was successfully reimported. However, when attempting to reindex, the following error was logged:

```bash
@84egi01cl
Error during job execution (org.tdl.vireo.search.impl.LuceneUpdateJob)

Execution exception (In /app/org/tdl/vireo/search/impl/LuceneUpdateJob.java around line 124)
NullPointerException occured : null

play.exceptions.JavaExecutionException
        at play.jobs.Job.call(Job.java:208)
        at play.jobs.Job$1.call(Job.java:117)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPool
Executor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecuto
r.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.tdl.vireo.search.impl.LuceneUpdateJob.writeIndex(LuceneUpdateJob.java:124)
        at org.tdl.vireo.search.impl.LuceneAbstractJobImpl.doJob(LuceneAbstractJobImpl.java:117)
        at play.jobs.Job.doJobWithResult(Job.java:53)
        at play.jobs.Job$2.apply(Job.java:196)
        at play.db.jpa.JPA.withTransaction(JPA.java:234)
        at play.db.jpa.JPA.withinFilter(JPA.java:195)
        at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
        at play.jobs.Job.withinFilter(Job.java:175)
        at play.jobs.Job.call(Job.java:194)
        ... 7 more

```

**Comment by jrgriffiniii** [comment]
Manually removing the corrupted Lucene index files, and then restarting the server, followed by reindexing, ensured that only the valid QA entries were properly imported.

**Comment by jrgriffiniii** [comment]
It was also necessary to once more reimport the QA submission records in order to ensure that the e-mail addresses follow the pattern `thesis.central.pu+[NET_ID]@gmail.com`.

**Comment by jrgriffiniii** [comment]
I have also confirmed that the account for Lynn Durgin has administrative privileges.

**Comment by jrgriffiniii** [comment]
Lynn has been notified by e-mail of the status of the QA deployment, and I have requested that this now be tested when she is next available.
