### ISSUE TITLE
ThesisCentral QA not processing submissions

### ISSUE THREAD

**Issue by kelynch** [pulibrary/drds_catchall#39]
When a user goes through the thesis submission process, after hitting the "confirm and submit" button at the last step:

![Screen Shot 2022-02-08 at 4 58 59 PM](https://user-images.githubusercontent.com/7795797/153082768-322dad7d-6e59-499f-b49e-aba7be8919e6.png)

The page hangs for a while, then we get a 500 error:

![Screen Shot 2022-02-08 at 4 45 31 PM](https://user-images.githubusercontent.com/7795797/153082701-b352fcbb-92cc-422f-84f7-0f30a533d470.png)

It looks like a 500 error from the console output.  This is blocking acceptance testing on ThesisCentral for 2021 submissions.

**Comment by jrgriffiniii** [comment]
The following errors were logged from within the QA server:

```bash
Execution exception (In /app/org/tdl/vireo/email/impl/EmailServiceImpl.java arou
nd line 176)
RuntimeException occured : org.apache.commons.mail.EmailException: Sending the e
mail to the following server failed : 127.0.0.1:25

play.exceptions.JavaExecutionException: org.apache.commons.mail.EmailException:
Sending the email to the following server failed : 127.0.0.1:25
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
        at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: org.apache.commons.mail.EmailException: S
ending the email to the following server failed : 127.0.0.1:25
        at org.tdl.vireo.email.impl.EmailServiceImpl$EmailJob.doJob(EmailService
Impl.java:176)
        at org.tdl.vireo.email.impl.EmailServiceImpl.sendEmail(EmailServiceImpl.
java:64)
        at org.tdl.vireo.services.EmailRuleService.sendEmail(EmailRuleService.ja
va:200)
        at org.tdl.vireo.services.EmailRuleService.runEmailRules(EmailRuleServic
e.java:48)
        at org.tdl.vireo.model.jpa.JpaSubmissionImpl.setState(JpaSubmissionImpl.
java:1187)
        at controllers.submit.Confirm.confirm(Confirm.java:95)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
        ... 1 more
Caused by: org.apache.commons.mail.EmailException: Sending the email to the foll
owing server failed : 127.0.0.1:25
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1401)
        at org.apache.commons.mail.Email.send(Email.java:1428)
        at org.tdl.vireo.email.impl.EmailServiceImpl$EmailJob.doJob(EmailService
Impl.java:160)
        ... 11 more
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 451 4.1.8 Domain of sender
 address noreply@princeton.edu does not resolve

        at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2
108)
        at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1609)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1117)
        at javax.mail.Transport.send0(Transport.java:195)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1391)
        ... 13 more
```

**Comment by jrgriffiniii** [comment]
This should now be functioning, as I am now successfully receiving e-mails from the QA server environment.

**Comment by jrgriffiniii** [comment]
This was related to the `sendmail` configuration, as well as the `postfix` configuration for the server. The `sendmail` PID file was not being properly written to within the `/run` directory, while the `postfix` process should *not* have been run along with `sendmail` (as this was binding to port 25)

**Comment by jrgriffiniii** [comment]
Also, please be aware that this was afflicting the production server environment as well. This should now also be resolved.

**Comment by kelynch** [comment]
Confirmed this is now working from stakeholder over email last week.
